# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Max Harney
tagline:          ''
description:      'Software Developer, Home Brewer, and Tabletop Gamer.'
baseurl:

author:
  name:           'Max Harney'
  url:            https://twitter.com/maxharney

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/maxharney/maxharney.com

plugins:
  - jekyll-gist
  - jekyll-paginate