# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Max Harney
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
baseurl:          /

author:
  name:           'Max Harney'
  url:            https://twitter.com/maxharney

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/maxharney/maxharney.com

plugins:
  - jekyll-gist
  - jekyll-paginate